language: java
jdk:
  - openjdk11

cache:
  directories:
  - $HOME/.m2
  
script:
  - mvn -B clean package 
  
after_success:
  - mvn -B clean verify jacoco:report jacoco:report-integration coveralls:report
